In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('emotions.txt', sep=';', header=None, names=['text', 'emotions'])
df.head()

                                                text emotions
0  im feeling rather rotten so im not very ambiti...  sadness
1          im updating my blog because i feel shitty  sadness
2  i never make her separate from me because i do...  sadness
3  i left with my bouquet of red and yellow tulip...      joy
4    i was feeling a little vain when i did this one  sadness

In [3]:
df.isnull().sum()

text        0
emotions    0
dtype: int64

In [4]:
unique_emotions = df['emotions'].unique()
emotion_number = {}
i = 0

for emo in unique_emotions:
    emotion_number[emo] = i
    i += 1

df['emotions'] = df['emotions'].map(emotion_number)
df

                                                   text  emotions
0     im feeling rather rotten so im not very ambiti...         0
1             im updating my blog because i feel shitty         0
2     i never make her separate from me because i do...         0
3     i left with my bouquet of red and yellow tulip...         1
4       i was feeling a little vain when i did this one         0
...                                                 ...       ...
1995  i just keep feeling like someone is being unki...         3
1996  im feeling a little cranky negative after this...         3
1997  i feel that i am useful to my people and that ...         1
1998  im feeling more comfortable with derby i feel ...         1
1999  i feel all weird when i have to meet w people ...         2

[2000 rows x 2 columns]

In [5]:
# Step 1 : Convert to Lower Case
df['text'] = df['text'].apply(lambda x : x.lower())
df.head()

                                                text  emotions
0  im feeling rather rotten so im not very ambiti...         0
1          im updating my blog because i feel shitty         0
2  i never make her separate from me because i do...         0
3  i left with my bouquet of red and yellow tulip...         1
4    i was feeling a little vain when i did this one         0

In [6]:
# Step 2 : Remove Punctuations
import string
def remove_punc(txt):
    return txt.translate(str.maketrans('','',string.punctuation))

In [7]:
df['text'] = df['text'].apply(remove_punc)
df.head()

                                                text  emotions
0  im feeling rather rotten so im not very ambiti...         0
1          im updating my blog because i feel shitty         0
2  i never make her separate from me because i do...         0
3  i left with my bouquet of red and yellow tulip...         1
4    i was feeling a little vain when i did this one         0

In [8]:
# Step 3 : Remove Numbers from Text
def remove_numbers(txt):
    new = ""
    for char in txt:
        if not char.isdigit():
            new += char
    return new

df['text'] = df['text'].apply(remove_numbers)

In [9]:
# Step 4 : Remove URLs
# Step 5 : Remove HTML Tags (Helpful in  Web Scrapped Data)

# Step 6: Remove Emoji's
def remove_emojis(txt):
    new = ""
    for char in txt:
        if char.isascii():
          new += char
    return new

df['text'] = df['text'].apply(remove_emojis)

In [10]:
# Step - 7 : Remove Stop Words (the, is, was etc...)
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [11]:
nltk.download('punkt_tab')
nltk.download('stopwords')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Soni\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Soni\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [12]:
stop_words = set(stopwords.words('english'))
len(stop_words)

198

In [13]:
df.loc[1]['text']

'im updating my blog because i feel shitty'

In [14]:
def remove(txt):
    words = word_tokenize(txt)
    cleaned = []

    for i in words:
        if not i in stop_words: 
            cleaned.append(i)
    
    return ' '.join(cleaned)

In [15]:
df['text'] = df['text'].apply(remove)
df.head()

                                                text  emotions
0        im feeling rather rotten im ambitious right         0
1                       im updating blog feel shitty         0
2    never make separate ever want feel like ashamed         0
3  left bouquet red yellow tulips arm feeling sli...         1
4                            feeling little vain one         0

In [16]:
df.loc[1]['text']

'im updating blog feel shitty'

In [17]:
#Bag of Words
from sklearn.feature_extraction.text import CountVectorizer

In [18]:
documents = [
    "I love pizza",
    "Pizza is the best",
    "I love pasta",
    "Pasta is great"
]

In [19]:
vectorizer = CountVectorizer(ngram_range=(2,2))

In [20]:
X = vectorizer.fit_transform(documents)

print("Vocabulary : ", vectorizer.get_feature_names_out())
print("\n Bag of Word Matrix : \n", X.toarray())

Vocabulary :  ['is great' 'is the' 'love pasta' 'love pizza' 'pasta is' 'pizza is'
 'the best']

 Bag of Word Matrix :
 [[0 0 0 1 0 0 0]
 [0 1 0 0 0 1 1]
 [0 0 1 0 0 0 0]
 [1 0 0 0 1 0 0]]

In [21]:
#TF-IDF
from sklearn.feature_extraction.text import TfidfVectorizer

tf_vectorizer = TfidfVectorizer()

In [22]:
Y = tf_vectorizer.fit_transform(documents)

print("Vocabulary : ", tf_vectorizer.get_feature_names_out())
print("\nTF-IDF Matrix : \n", Y.toarray())

Vocabulary :  ['best' 'great' 'is' 'love' 'pasta' 'pizza' 'the']

TF-IDF Matrix :
 [[0.         0.         0.         0.70710678 0.         0.70710678
  0.        ]
 [0.55528266 0.         0.43779123 0.         0.         0.43779123
  0.55528266]
 [0.         0.         0.         0.70710678 0.70710678 0.
  0.        ]
 [0.         0.66767854 0.52640543 0.         0.52640543 0.
  0.        ]]

In [23]:
from sklearn.model_selection import train_test_split

X = df['text']
y = df['emotions']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [24]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

In [25]:
bow_vectorizer = CountVectorizer()

In [26]:
X_train_bow = bow_vectorizer.fit_transform(X_train)
X_test_bow = bow_vectorizer.transform(X_test)

In [27]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

model = MultinomialNB(alpha=0.3)

In [28]:
model.fit(X_train_bow, y_train)

MultinomialNB(alpha=0.3)

In [29]:
y_pred = model.predict(X_test_bow)

print("Accuracy using Bag of Words : " , accuracy_score(y_test, y_pred))

Accuracy using Bag of Words :  0.66

In [30]:
#Using TF-IDF Now Finding Accuracy
tfidf_vectorizer = TfidfVectorizer()

In [31]:
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)

In [32]:
nb2_model = MultinomialNB(alpha=0.1)

In [33]:
nb2_model.fit(X_train_tfidf, y_train)

MultinomialNB(alpha=0.1)

In [34]:
y_pred_nb2 = nb2_model.predict(X_test_tfidf)

print("Accuracy : ", accuracy_score(y_pred_nb2, y_test))

Accuracy :  0.6825

In [48]:
from sklearn.linear_model import LogisticRegression

lr_model = LogisticRegression()

In [49]:
lr_model.fit(X_train_tfidf, y_train)

LogisticRegression()

In [50]:
y_pred_lr = lr_model.predict(X_test_tfidf)

print("Accuracy : ", accuracy_score(y_pred_lr, y_test))

Accuracy :  0.6375