In [35]:
import pandas as pd
import numpy as np
import seaborn as sns
import warnings

warnings.filterwarnings('ignore')

In [36]:
df = pd.read_csv('OnlineRetail.csv', encoding='latin-1')
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,01-12-2010 08:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,01-12-2010 08:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,01-12-2010 08:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,01-12-2010 08:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,01-12-2010 08:26,3.39,17850.0,United Kingdom

In [37]:
from sklearn.cluster import KMeans
from kmodes.kmodes import KModes
from pyclustering.cluster.kmedoids import kmedoids

from sklearn.preprocessing import LabelEncoder

In [38]:
encode = LabelEncoder()
cols = df.columns
for col in cols:
    df[col] = encode.fit_transform(df[col])
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,0,3536,3918,334,606,182,4048,36
1,0,2794,3926,334,606,228,4048,36
2,0,3044,913,336,606,190,4048,36
3,0,2985,1910,334,606,228,4048,36
4,0,2984,2911,334,606,228,4048,36

In [39]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [40]:
X_scaled = scaler.fit_transform(df)
X_scaled

array([[-1.73075996,  2.02111495,  1.55062094, ..., -0.05057229,
         0.91702867,  0.27965099],
       [-1.73075996,  1.22566499,  1.55758319, ...,  0.29451572,
         0.91702867,  0.27965099],
       [-1.73075996,  1.49367373, -1.06457634, ...,  0.00944302,
         0.91702867,  0.27965099],
       ...,
       [ 1.54695717,  0.52991428, -1.20730258, ...,  0.57208651,
        -1.69558134, -3.41640162],
       [ 1.54695717,  0.53098632, -1.20817287, ...,  0.57208651,
        -1.69558134, -3.41640162],
       [ 1.54695717, -0.59786652, -1.59457805, ...,  0.81214774,
        -1.69558134, -3.41640162]], shape=(541909, 8))

In [41]:
# model_kmeans = KMeans(n_clusters=4, random_state=42)
labels = model_kmeans.fit_predict(X_scaled)

In [42]:
# from sklearn.metrics import silhouette_score
print(silhouette_score(X_scaled, labels, sample_size=100))

0.12099496737314805

In [34]:
# #KModes
model_kmodes = KModes(n_clusters=4, random_state=42)
labels = model_kmodes.fit_predict(X_scaled)
print(silhouette_score(X_scaled, labels, sample_size=100))

-0.04908736281823844

In [43]:
#KMedoid
from sklearn_extra.cluster import KMedoids
model_kmedoids = KMedoids(n_cluster = 4)
labels = model_kmedoids.fit_predict(X_scaled)
print(silhouette_score(X_scaled[:1000], labels[:1000], sample_size=1000))

ModuleNotFoundError: No module named 'sklearn_extra'

In [28]:
#AGNES
from sklearn.cluster._agglomerative import AgglomerativeClustering
model_agnes = AgglomerativeClustering(n_clusters=4)
labels = model_agnes.fit_predict(X_scaled[:1000])
print(silhouette_score(X_scaled[:1000], labels[:1000], sample_size=1000))

0.27885605256367807

In [33]:
#DIANA
from scipy.cluster.hierarchy import linkage, fcluster
Z = linkage(X_scaled[:1000], method='single')
labels = fcluster(Z, t=4, criterion='maxclust')
print(silhouette_score(X_scaled[:1000], labels))

0.4827100393202758